"""remove_ai_tables

Revision ID: 03467261cc0e
Revises: 28c7a91b63bf
Create Date: 2026-09-08 20:38:00.496896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03467261cc0e'
down_revision: Union[str, None] = '28c7a91b63bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obsidian_sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obsidian_sync_run_id'), 'obsidian_sync_run', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'BAN_STUDENT', 'UNBAN_STUDENT', 'RUN_IRT', 'BACKUP_DB', 'OTHER', name='auditaction'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('exam_generation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('num_forms', sa.Integer(), nullable=False),
    sa.Column('distinct_questions', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='examgenerationstatus'), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_generation_run_id'), 'exam_generation_run', ['id'], unique=False)
    op.create_table('omr_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='omrjobstatus'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_omr_job_id'), 'omr_job', ['id'], unique=False)
    op.create_table('item_analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ctt_difficulty', sa.Float(), nullable=True),
    sa.Column('ctt_discrimination', sa.Float(), nullable=True),
    sa.Column('ctt_distractor_label', sa.String(length=50), nullable=True),
    sa.Column('irt_a', sa.Float(), nullable=True),
    sa.Column('irt_b', sa.Float(), nullable=True),
    sa.Column('irt_a_se', sa.Float(), nullable=True),
    sa.Column('irt_b_se', sa.Float(), nullable=True),
    sa.Column('chi_square_p', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_analysis_result_exam_id'), 'item_analysis_result', ['exam_id'], unique=False)
    op.create_index(op.f('ix_item_analysis_result_id'), 'item_analysis_result', ['id'], unique=False)
    op.create_index(op.f('ix_item_analysis_result_question_id'), 'item_analysis_result', ['question_id'], unique=False)
    op.create_table('obsidian_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_obsidian_file_path')
    )
    op.create_index(op.f('ix_obsidian_file_file_path'), 'obsidian_file', ['file_path'], unique=False)
    op.create_index(op.f('ix_obsidian_file_id'), 'obsidian_file', ['id'], unique=False)
    op.create_table('omr_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('student_id_raw', sa.String(length=50), nullable=True),
    sa.Column('form_code_raw', sa.String(length=50), nullable=True),
    sa.Column('answers_raw', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'NEEDS_REVIEW', 'COMPLETED', 'FAILED', name='omrsheetstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('exam_submission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_submission_id'], ['exam_submission.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['omr_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_omr_sheet_id'), 'omr_sheet', ['id'], unique=False)
    op.create_foreign_key(None, 'exam_form_question', 'exam_generation_run', ['exam_generation_run_id'], ['id'])
    op.create_index(op.f('ix_knowledge_node_parent_id'), 'knowledge_node', ['parent_id'], unique=False)
    op.add_column('matrix_rule_group', sa.Column('group_mode', sa.String(length=20), server_default='ATOMIC', nullable=False))
    op.alter_column('question', 'knowledge_node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_question_knowledge_node_id'), 'question', ['knowledge_node_id'], unique=False)
    op.add_column('resource', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('resource', sa.Column('url', sa.Text(), nullable=True))
    op.alter_column('resource', 'type',
               existing_type=postgresql.ENUM('IMAGE', 'PDF', 'TEXT', name='resourcetype'),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_constraint('resource_uploader_id_fkey', 'resource', type_='foreignkey')
    op.drop_column('resource', 'size_bytes')
    op.drop_column('resource', 'uploader_id')
    op.drop_column('resource', 'created_at')
    op.drop_column('resource', 'original_name')
    op.drop_column('resource', 'mime_type')
    op.drop_column('resource', 'content_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('content_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('mime_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('original_name', sa.VARCHAR(length=255), server_default=sa.text("'resource'::character varying"), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_foreign_key('resource_uploader_id_fkey', 'resource', 'user', ['uploader_id'], ['id'])
    op.alter_column('resource', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('IMAGE', 'PDF', 'TEXT', name='resourcetype'),
               nullable=False)
    op.drop_column('resource', 'url')
    op.drop_column('resource', 'name')
    op.drop_index(op.f('ix_question_knowledge_node_id'), table_name='question')
    op.alter_column('question', 'knowledge_node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('matrix_rule_group', 'group_mode')
    op.drop_index(op.f('ix_knowledge_node_parent_id'), table_name='knowledge_node')
    op.drop_constraint(None, 'exam_form_question', type_='foreignkey')
    op.drop_index(op.f('ix_omr_sheet_id'), table_name='omr_sheet')
    op.drop_table('omr_sheet')
    op.drop_index(op.f('ix_obsidian_file_id'), table_name='obsidian_file')
    op.drop_index(op.f('ix_obsidian_file_file_path'), table_name='obsidian_file')
    op.drop_table('obsidian_file')
    op.drop_index(op.f('ix_item_analysis_result_question_id'), table_name='item_analysis_result')
    op.drop_index(op.f('ix_item_analysis_result_id'), table_name='item_analysis_result')
    op.drop_index(op.f('ix_item_analysis_result_exam_id'), table_name='item_analysis_result')
    op.drop_table('item_analysis_result')
    op.drop_index(op.f('ix_omr_job_id'), table_name='omr_job')
    op.drop_table('omr_job')
    op.drop_index(op.f('ix_exam_generation_run_id'), table_name='exam_generation_run')
    op.drop_table('exam_generation_run')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_obsidian_sync_run_id'), table_name='obsidian_sync_run')
    op.drop_table('obsidian_sync_run')
    # ### end Alembic commands ###
