"""Add attempt_number to exam_participant unique constraint

Revision ID: 03d8b3cf0c4b
Revises: 22921cb607ca
Create Date: 2026-09-13 11:38:30.714999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d8b3cf0c4b'
down_revision: Union[str, None] = '22921cb607ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exam_form_exam_code', 'exam_form', ['exam_id', 'code'])
    op.create_unique_constraint('uq_exam_participant_exam_user_attempt', 'exam_participant', ['exam_id', 'user_id', 'attempt_number'])
    op.drop_constraint(op.f('exam_participant_suspended_by_id_fkey'), 'exam_participant', type_='foreignkey')
    op.create_foreign_key(None, 'exam_participant', 'user', ['suspended_by_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_submission_answer_question', 'exam_submission_answer', ['exam_submission_id', 'exam_form_question_id'])
    op.drop_constraint(op.f('knowledge_node_parent_id_fkey'), 'knowledge_node', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_node', 'knowledge_node', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('question_parent_question_id_fkey'), 'question', type_='foreignkey')
    op.drop_constraint(op.f('question_creator_id_fkey'), 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'question', ['parent_question_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'question', 'user', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(op.f('question_creator_id_fkey'), 'question', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('question_parent_question_id_fkey'), 'question', 'question', ['parent_question_id'], ['id'])
    op.drop_constraint(None, 'knowledge_node', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_node_parent_id_fkey'), 'knowledge_node', 'knowledge_node', ['parent_id'], ['id'])
    op.drop_constraint('uq_submission_answer_question', 'exam_submission_answer', type_='unique')
    op.drop_constraint(None, 'exam_participant', type_='foreignkey')
    op.create_foreign_key(op.f('exam_participant_suspended_by_id_fkey'), 'exam_participant', 'user', ['suspended_by_id'], ['id'])
    op.drop_constraint('uq_exam_participant_exam_user_attempt', 'exam_participant', type_='unique')
    op.create_unique_constraint('uq_exam_participant_exam_user', 'exam_participant', ['exam_id', 'user_id'])
    op.drop_constraint('uq_exam_form_exam_code', 'exam_form', type_='unique')
    # ### end Alembic commands ###
