"""Add ItemAnalysisResult

Revision ID: 0ec5b1337c2a
Revises: fd2d3c6791cc
Create Date: 2026-08-30 18:39:39.779780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec5b1337c2a'
down_revision: Union[str, None] = 'fd2d3c6791cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ctt_difficulty', sa.Float(), nullable=True),
    sa.Column('ctt_discrimination', sa.Float(), nullable=True),
    sa.Column('ctt_distractor_label', sa.String(length=50), nullable=True),
    sa.Column('irt_a', sa.Float(), nullable=True),
    sa.Column('irt_b', sa.Float(), nullable=True),
    sa.Column('irt_a_se', sa.Float(), nullable=True),
    sa.Column('irt_b_se', sa.Float(), nullable=True),
    sa.Column('chi_square_p', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_analysis_result_exam_id'), 'item_analysis_result', ['exam_id'], unique=False)
    op.create_index(op.f('ix_item_analysis_result_id'), 'item_analysis_result', ['id'], unique=False)
    op.create_index(op.f('ix_item_analysis_result_question_id'), 'item_analysis_result', ['question_id'], unique=False)
    op.add_column('irt_task', sa.Column('error_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irt_task', 'error_details')
    op.drop_index(op.f('ix_item_analysis_result_question_id'), table_name='item_analysis_result')
    op.drop_index(op.f('ix_item_analysis_result_id'), table_name='item_analysis_result')
    op.drop_index(op.f('ix_item_analysis_result_exam_id'), table_name='item_analysis_result')
    op.drop_table('item_analysis_result')
    # ### end Alembic commands ###
