"""matrix_v2

Revision ID: 122383431f91
Revises: 96da6a1099b7
Create Date: 2026-08-29 15:30:39.662611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122383431f91'
down_revision: Union[str, None] = '96da6a1099b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_generation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('num_forms', sa.Integer(), nullable=False),
    sa.Column('distinct_questions', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='examgenerationstatus'), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_generation_run_id'), 'exam_generation_run', ['id'], unique=False)
    op.add_column('exam_form_question', sa.Column('matrix_rule_id', sa.Integer(), nullable=True))
    op.add_column('exam_form_question', sa.Column('exam_generation_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam_form_question', 'exam_generation_run', ['exam_generation_run_id'], ['id'])
    op.create_foreign_key(None, 'exam_form_question', 'matrix_rule', ['matrix_rule_id'], ['id'])
    
    knowledgenodetype = sa.Enum('TOPIC', 'CONCEPT', 'SKILL', name='knowledgenodetype')
    knowledgenodetype.create(op.get_bind(), checkfirst=True)
    
    op.add_column('knowledge_node', sa.Column('node_type', knowledgenodetype, nullable=False, server_default='SKILL'))
    op.add_column('knowledge_node', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('matrix', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('matrix_rule', sa.Column('target_irt_b', sa.Float(), nullable=True))
    op.add_column('matrix_rule', sa.Column('position', sa.Integer(), nullable=False))
    
    op.execute("""
    CREATE OR REPLACE VIEW v_question_exposure AS
    SELECT
        q.id AS question_id,
        COUNT(efq.id) AS exposure_count
    FROM question q
    LEFT JOIN exam_form_question efq ON efq.question_id = q.id
    LEFT JOIN exam_form ef ON ef.id = efq.exam_form_id
    LEFT JOIN exam e ON e.id = ef.exam_id AND e.status = 'PUBLISHED'
    GROUP BY q.id;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrix_rule', 'position')
    op.drop_column('matrix_rule', 'target_irt_b')
    op.drop_column('matrix', 'subject')
    op.drop_column('knowledge_node', 'subject')
    op.drop_column('knowledge_node', 'node_type')
    knowledgenodetype = sa.Enum('TOPIC', 'CONCEPT', 'SKILL', name='knowledgenodetype')
    knowledgenodetype.drop(op.get_bind(), checkfirst=True)
    
    op.drop_constraint(None, 'exam_form_question', type_='foreignkey')
    op.drop_constraint(None, 'exam_form_question', type_='foreignkey')
    op.drop_column('exam_form_question', 'exam_generation_run_id')
    op.drop_column('exam_form_question', 'matrix_rule_id')
    op.drop_index(op.f('ix_exam_generation_run_id'), table_name='exam_generation_run')
    op.drop_table('exam_generation_run')
    
    op.execute("DROP VIEW IF EXISTS v_question_exposure;")
    # ### end Alembic commands ###
