"""add group_mode to matrix_rule_group

Revision ID: 129f0b9b29e6
Revises: 28c7a91b63bf
Create Date: 2026-09-11 14:27:23.011754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '129f0b9b29e6'
down_revision: Union[str, None] = '28c7a91b63bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'allow_omr',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'exam_form_question', 'exam_generation_run', ['exam_generation_run_id'], ['id'])
    op.create_index(op.f('ix_knowledge_node_parent_id'), 'knowledge_node', ['parent_id'], unique=False)
    op.add_column('matrix_rule_group', sa.Column('group_mode', sa.String(length=20), server_default='ATOMIC', nullable=False))
    op.alter_column('notification', 'is_global',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('question', 'knowledge_node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_question_knowledge_node_id'), 'question', ['knowledge_node_id'], unique=False)
    op.add_column('resource', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('resource', sa.Column('url', sa.Text(), nullable=True))
    op.alter_column('resource', 'type',
               existing_type=postgresql.ENUM('IMAGE', 'PDF', 'TEXT', name='resourcetype'),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_constraint(op.f('resource_uploader_id_fkey'), 'resource', type_='foreignkey')
    op.drop_column('resource', 'created_at')
    op.drop_column('resource', 'original_name')
    op.drop_column('resource', 'mime_type')
    op.drop_column('resource', 'content_url')
    op.drop_column('resource', 'size_bytes')
    op.drop_column('resource', 'uploader_id')
    op.alter_column('user', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'UNVERIFIED'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'UNVERIFIED'::character varying"))
    op.add_column('resource', sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('content_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('mime_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('original_name', sa.VARCHAR(length=255), server_default=sa.text("'resource'::character varying"), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('resource_uploader_id_fkey'), 'resource', 'user', ['uploader_id'], ['id'])
    op.alter_column('resource', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('IMAGE', 'PDF', 'TEXT', name='resourcetype'),
               nullable=False)
    op.drop_column('resource', 'url')
    op.drop_column('resource', 'name')
    op.drop_index(op.f('ix_question_knowledge_node_id'), table_name='question')
    op.alter_column('question', 'knowledge_node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification', 'is_global',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('matrix_rule_group', 'group_mode')
    op.drop_index(op.f('ix_knowledge_node_parent_id'), table_name='knowledge_node')
    op.drop_constraint(None, 'exam_form_question', type_='foreignkey')
    op.alter_column('exam', 'allow_omr',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
