"""Add Exam Session and Participants

Revision ID: 1bc47ffba2e6
Revises: f3b17e24dd47
Create Date: 2026-08-09 20:29:13.917461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc47ffba2e6'
down_revision: Union[str, None] = 'f3b17e24dd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_form_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', name='participantstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submit_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_form_id'], ['exam_form.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_participant_id'), 'exam_participant', ['id'], unique=False)
    op.add_column('exam', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('exam', sa.Column('show_score_mode', sa.String(length=50), nullable=False))
    op.add_column('exam', sa.Column('show_answer_mode', sa.String(length=50), nullable=False))
    op.add_column('exam', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'COMPLETED', name='examstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'status')
    op.drop_column('exam', 'show_answer_mode')
    op.drop_column('exam', 'show_score_mode')
    op.drop_column('exam', 'duration_minutes')
    op.drop_column('exam', 'end_time')
    op.drop_column('exam', 'start_time')
    op.drop_index(op.f('ix_exam_participant_id'), table_name='exam_participant')
    op.drop_table('exam_participant')
    # ### end Alembic commands ###
