"""Add Passage and public_code

Revision ID: 28c3d855a747
Revises: c6d059a7bb56
Create Date: 2026-08-29 21:20:48.571762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c3d855a747'
down_revision: Union[str, None] = 'c6d059a7bb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_code', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_author', sa.String(length=255), nullable=True),
    sa.Column('source_title', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passage_id'), 'passage', ['id'], unique=False)
    op.create_index(op.f('ix_passage_public_code'), 'passage', ['public_code'], unique=True)
    op.add_column('question', sa.Column('public_code', sa.String(length=50), nullable=True))
    op.add_column('question', sa.Column('passage_id', sa.Integer(), nullable=True))
    
    # Custom backfill logic
    import uuid
    bind = op.get_bind()
    questions = bind.execute(sa.text('SELECT id FROM question')).fetchall()
    for q in questions:
        new_code = f"q_{uuid.uuid4().hex[:12]}"
        bind.execute(
            sa.text('UPDATE question SET public_code = :code WHERE id = :id'),
            {"code": new_code, "id": q.id}
        )
    
    # Alter column to make it not nullable
    op.alter_column('question', 'public_code', existing_type=sa.String(length=50), nullable=False)

    op.create_index(op.f('ix_question_public_code'), 'question', ['public_code'], unique=True)
    # The foreign key name needs to be specified for SQLite/Postgres. Autogenerate omitted the name.
    op.create_foreign_key('fk_question_passage_id', 'question', 'passage', ['passage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_question_passage_id', 'question', type_='foreignkey')
    op.drop_index(op.f('ix_question_public_code'), table_name='question')
    op.drop_column('question', 'passage_id')
    op.drop_column('question', 'public_code')
    op.drop_index(op.f('ix_passage_public_code'), table_name='passage')
    op.drop_index(op.f('ix_passage_id'), table_name='passage')
    op.drop_table('passage')
    # ### end Alembic commands ###
