"""Add Grading Models

Revision ID: 55d479266b8c
Revises: a9a4d8e8f8fa
Create Date: 2026-08-09 20:44:56.993234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d479266b8c'
down_revision: Union[str, None] = 'a9a4d8e8f8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irt_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irt_task_id'), 'irt_task', ['id'], unique=False)
    op.create_table('exam_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_submission_id', sa.Integer(), nullable=False),
    sa.Column('ctt_score_part1', sa.Float(), nullable=False),
    sa.Column('ctt_score_part2', sa.Float(), nullable=False),
    sa.Column('ctt_score_part3', sa.Float(), nullable=False),
    sa.Column('ctt_score_part4', sa.Float(), nullable=False),
    sa.Column('irt_score_part1', sa.Float(), nullable=True),
    sa.Column('irt_score_part2', sa.Float(), nullable=True),
    sa.Column('irt_score_part3', sa.Float(), nullable=True),
    sa.Column('irt_score_part4', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_submission_id'], ['exam_submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_submission_id')
    )
    op.create_index(op.f('ix_exam_result_id'), 'exam_result', ['id'], unique=False)
    op.add_column('question', sa.Column('a_param', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('question', sa.Column('b_param', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('question', sa.Column('c_param', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('question', sa.Column('is_calibrated', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_calibrated')
    op.drop_column('question', 'c_param')
    op.drop_column('question', 'b_param')
    op.drop_column('question', 'a_param')
    op.drop_index(op.f('ix_exam_result_id'), table_name='exam_result')
    op.drop_table('exam_result')
    op.drop_index(op.f('ix_irt_task_id'), table_name='irt_task')
    op.drop_table('irt_task')
    # ### end Alembic commands ###
