"""Add matrix_rule_group

Revision ID: 63ea737ec776
Revises: e6cfc9d6c5b6
Create Date: 2026-08-30 11:46:34.387527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ea737ec776'
down_revision: Union[str, None] = 'e6cfc9d6c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_node_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_node.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_node_link_id'), 'knowledge_node_link', ['id'], unique=False)
    op.create_table('matrix_rule_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('required_passage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.ForeignKeyConstraint(['required_passage_id'], ['passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_rule_group_id'), 'matrix_rule_group', ['id'], unique=False)
    op.add_column('knowledge_node', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('matrix_rule', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matrix_rule', 'matrix_rule_group', ['group_id'], ['id'])
    op.alter_column('question', 'public_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'public_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'matrix_rule', type_='foreignkey')
    op.drop_column('matrix_rule', 'group_id')
    op.drop_column('knowledge_node', 'note')
    op.drop_index(op.f('ix_matrix_rule_group_id'), table_name='matrix_rule_group')
    op.drop_table('matrix_rule_group')
    op.drop_index(op.f('ix_knowledge_node_link_id'), table_name='knowledge_node_link')
    op.drop_table('knowledge_node_link')
    # ### end Alembic commands ###
