"""Add source_author and source_title to question

Revision ID: 65ad56c37b39
Revises: 122383431f91
Create Date: 2026-08-29 16:45:05.976752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ad56c37b39'
down_revision: Union[str, None] = '122383431f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('source_author', sa.String(length=255), nullable=True))
    op.add_column('question', sa.Column('source_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'source_title')
    op.drop_column('question', 'source_author')
    # ### end Alembic commands ###
