"""Add supabase_id to User

Revision ID: 88482ea72930
Revises: a4e5f6b7c8d9
Create Date: 2026-08-26 11:12:40.875635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88482ea72930'
down_revision: Union[str, None] = 'a4e5f6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_result', sa.Column('item_subitem_scores', sa.JSON(), nullable=True))
    op.add_column('exam_result', sa.Column('item_types', sa.JSON(), nullable=True))
    op.add_column('exam_result', sa.Column('correct_answers', sa.JSON(), nullable=True))
    op.add_column('exam_result', sa.Column('selected_answers', sa.JSON(), nullable=True))
    op.add_column('exam_result', sa.Column('item_points', sa.JSON(), nullable=True))
    op.add_column('exam_result', sa.Column('total_points', sa.Float(), nullable=True))
    op.add_column('exam_submission_answer', sa.Column('selected_answer_ids', sa.JSON(), nullable=True))
    op.add_column('exam_submission_answer', sa.Column('selected_subitem_answers', sa.JSON(), nullable=True))
    op.add_column('exam_submission_answer', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('supabase_id', sa.String(length=36), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_user_supabase_id'), 'user', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supabase_id'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'supabase_id')
    op.drop_column('exam_submission_answer', 'score')
    op.drop_column('exam_submission_answer', 'selected_subitem_answers')
    op.drop_column('exam_submission_answer', 'selected_answer_ids')
    op.drop_column('exam_result', 'total_points')
    op.drop_column('exam_result', 'item_points')
    op.drop_column('exam_result', 'selected_answers')
    op.drop_column('exam_result', 'correct_answers')
    op.drop_column('exam_result', 'item_types')
    op.drop_column('exam_result', 'item_subitem_scores')
    # ### end Alembic commands ###
