"""Add can_view_answers to User

Revision ID: 96da6a1099b7
Revises: 88482ea72930
Create Date: 2026-08-28 09:51:12.515092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96da6a1099b7'
down_revision: Union[str, None] = '88482ea72930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('can_view_answers', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_view_answers')
    # ### end Alembic commands ###
