"""migrate knowledge node to dag

Revision ID: a6b0ec018166
Revises: b7a1c9d4e2f8
Create Date: 2026-08-31 12:22:15.766513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b0ec018166'
down_revision: Union[str, None] = 'b7a1c9d4e2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_node_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['knowledge_node.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_node_parent_child_id'), 'knowledge_node_parent', ['child_id'], unique=False)
    op.create_index(op.f('ix_knowledge_node_parent_id'), 'knowledge_node_parent', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_node_parent_parent_id'), 'knowledge_node_parent', ['parent_id'], unique=False)
    op.add_column('knowledge_node', sa.Column('short_code', sa.String(length=50), nullable=True))
    op.add_column('knowledge_node', sa.Column('path_code', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_knowledge_node_path_code'), 'knowledge_node', ['path_code'], unique=False)
    op.create_index(op.f('ix_knowledge_node_short_code'), 'knowledge_node', ['short_code'], unique=False)
    # ### end Alembic commands ###

    # Data migration: Transfer existing parent_id to the new DAG table as primary parents
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id, parent_id FROM knowledge_node WHERE parent_id IS NOT NULL"))
    for row in result:
        connection.execute(
            sa.text("INSERT INTO knowledge_node_parent (child_id, parent_id, is_primary) VALUES (:child, :parent, :primary)"),
            {"child": row[0], "parent": row[1], "primary": True}
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_node_short_code'), table_name='knowledge_node')
    op.drop_index(op.f('ix_knowledge_node_path_code'), table_name='knowledge_node')
    op.drop_column('knowledge_node', 'path_code')
    op.drop_column('knowledge_node', 'short_code')
    op.drop_index(op.f('ix_knowledge_node_parent_parent_id'), table_name='knowledge_node_parent')
    op.drop_index(op.f('ix_knowledge_node_parent_id'), table_name='knowledge_node_parent')
    op.drop_index(op.f('ix_knowledge_node_parent_child_id'), table_name='knowledge_node_parent')
    op.drop_table('knowledge_node_parent')
    # ### end Alembic commands ###
