"""Add Exam Submissions and Tracking Logs

Revision ID: a9a4d8e8f8fa
Revises: 1bc47ffba2e6
Create Date: 2026-08-09 20:35:23.881615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a4d8e8f8fa'
down_revision: Union[str, None] = '1bc47ffba2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_participant_id', sa.Integer(), nullable=False),
    sa.Column('submit_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_participant_id'], ['exam_participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_submission_id'), 'exam_submission', ['id'], unique=False)
    op.create_table('exam_tracking_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_participant_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_participant_id'], ['exam_participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_tracking_log_id'), 'exam_tracking_log', ['id'], unique=False)
    op.create_table('exam_submission_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_submission_id', sa.Integer(), nullable=False),
    sa.Column('exam_form_question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_form_question_id'], ['exam_form_question.id'], ),
    sa.ForeignKeyConstraint(['exam_submission_id'], ['exam_submission.id'], ),
    sa.ForeignKeyConstraint(['selected_answer_id'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_submission_answer_id'), 'exam_submission_answer', ['id'], unique=False)
    op.add_column('exam_participant', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_participant', 'device_fingerprint')
    op.drop_index(op.f('ix_exam_submission_answer_id'), table_name='exam_submission_answer')
    op.drop_table('exam_submission_answer')
    op.drop_index(op.f('ix_exam_tracking_log_id'), table_name='exam_tracking_log')
    op.drop_table('exam_tracking_log')
    op.drop_index(op.f('ix_exam_submission_id'), table_name='exam_submission')
    op.drop_table('exam_submission')
    # ### end Alembic commands ###
