"""add registration_number to user

Revision ID: b9b1f933c7a3
Revises: bccea913212d
Create Date: 2026-09-02 15:05:22.873452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b1f933c7a3'
down_revision: Union[str, None] = 'bccea913212d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_number', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_user_registration_number'), 'user', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registration_number'), table_name='user')
    op.drop_column('user', 'registration_number')
    # ### end Alembic commands ###
