"""remove level_distribution from matrix_rule

Revision ID: bccea913212d
Revises: c1234567890a
Create Date: 2026-09-02 09:20:24.471819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bccea913212d'
down_revision: Union[str, None] = 'c1234567890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_submission_answer', sa.Column('text_answer', sa.String(length=500), nullable=True))
    op.drop_column('matrix_rule', 'level_distribution')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_rule', sa.Column('level_distribution', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('exam_submission_answer', 'text_answer')
    # ### end Alembic commands ###
