"""add max attempts

Revision ID: c69794f84d66
Revises: 6754a9df4ade
Create Date: 2026-09-13 10:50:50.505733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69794f84d66'
down_revision: Union[str, None] = '6754a9df4ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_answer_question_id', 'answer', ['question_id'], unique=False)
    op.add_column('exam', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('exam_participant', sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_exam_participant_exam_user', 'exam_participant', ['exam_id', 'user_id'], unique=False)
    op.create_index('ix_exam_submission_participant', 'exam_submission', ['exam_participant_id'], unique=False)
    op.alter_column('matrix_rule', 'note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_otp_email_code_purpose', 'otp_token', ['email', 'code', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_email_code_purpose', table_name='otp_token')
    op.alter_column('matrix_rule', 'note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('ix_exam_submission_participant', table_name='exam_submission')
    op.drop_index('ix_exam_participant_exam_user', table_name='exam_participant')
    op.drop_column('exam_participant', 'attempt_number')
    op.drop_column('exam', 'max_attempts')
    op.drop_index('ix_answer_question_id', table_name='answer')
    # ### end Alembic commands ###
