"""add reject_reason to question

Revision ID: c6d059a7bb56
Revises: 65ad56c37b39
Create Date: 2026-08-29 18:43:12.911517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d059a7bb56'
down_revision: Union[str, None] = '65ad56c37b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('reject_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'reject_reason')
    # ### end Alembic commands ###
