"""add_suspended_status_and_fields

Revision ID: d43dac9bbb93
Revises: 63ea737ec776
Create Date: 2026-08-30 13:14:24.826848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43dac9bbb93'
down_revision: Union[str, None] = '63ea737ec776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_participant', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_participant', sa.Column('suspended_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam_participant', 'user', ['suspended_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_participant', type_='foreignkey')
    op.drop_column('exam_participant', 'suspended_by_id')
    op.drop_column('exam_participant', 'suspended_at')
    # ### end Alembic commands ###
