"""add otp_token table

Revision ID: e8c48dfbd877
Revises: b9b1f933c7a3
Create Date: 2026-09-02 16:47:02.220699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c48dfbd877'
down_revision: Union[str, None] = 'b9b1f933c7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_token_email'), 'otp_token', ['email'], unique=False)
    op.create_index(op.f('ix_otp_token_id'), 'otp_token', ['id'], unique=False)
    op.create_index(op.f('ix_otp_token_purpose'), 'otp_token', ['purpose'], unique=False)
    op.create_table('question_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_embedding_id'), 'question_embedding', ['id'], unique=False)
    op.create_index(op.f('ix_question_embedding_question_id'), 'question_embedding', ['question_id'], unique=True)
    op.alter_column('exam', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('question_skill_tag_question_id_fkey', 'question_skill_tag', type_='foreignkey')
    op.create_foreign_key(None, 'question_skill_tag', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_skill_tag', type_='foreignkey')
    op.create_foreign_key('question_skill_tag_question_id_fkey', 'question_skill_tag', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_question_embedding_question_id'), table_name='question_embedding')
    op.drop_index(op.f('ix_question_embedding_id'), table_name='question_embedding')
    op.drop_table('question_embedding')
    op.drop_index(op.f('ix_otp_token_purpose'), table_name='otp_token')
    op.drop_index(op.f('ix_otp_token_id'), table_name='otp_token')
    op.drop_index(op.f('ix_otp_token_email'), table_name='otp_token')
    op.drop_table('otp_token')
    # ### end Alembic commands ###
