"""Add Exam tables

Revision ID: f3b17e24dd47
Revises: 515449d82440
Create Date: 2026-08-09 20:24:22.489037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b17e24dd47'
down_revision: Union[str, None] = '515449d82440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_id'), 'matrix', ['id'], unique=False)
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_id'), 'exam', ['id'], unique=False)
    op.create_table('matrix_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE', 'FILL_IN_BLANK', name='questiontype'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_node.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_rule_id'), 'matrix_rule', ['id'], unique=False)
    op.create_table('exam_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_form_id'), 'exam_form', ['id'], unique=False)
    op.create_table('exam_form_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_form_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_form_id'], ['exam_form.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_form_question_id'), 'exam_form_question', ['id'], unique=False)
    op.create_table('exam_form_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_form_question_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('new_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['exam_form_question_id'], ['exam_form_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_form_answer_id'), 'exam_form_answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_form_answer_id'), table_name='exam_form_answer')
    op.drop_table('exam_form_answer')
    op.drop_index(op.f('ix_exam_form_question_id'), table_name='exam_form_question')
    op.drop_table('exam_form_question')
    op.drop_index(op.f('ix_exam_form_id'), table_name='exam_form')
    op.drop_table('exam_form')
    op.drop_index(op.f('ix_matrix_rule_id'), table_name='matrix_rule')
    op.drop_table('matrix_rule')
    op.drop_index(op.f('ix_exam_id'), table_name='exam')
    op.drop_table('exam')
    op.drop_index(op.f('ix_matrix_id'), table_name='matrix')
    op.drop_table('matrix')
    # ### end Alembic commands ###
