"""Add note to MatrixRule

Revision ID: ffae5d6f8264
Revises: add_render_style_01
Create Date: 2026-09-11 20:27:45.265402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffae5d6f8264'
down_revision: Union[str, None] = 'add_render_style_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_rule', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrix_rule', 'note')
    # ### end Alembic commands ###
